""" contains all details on a person that are relevant and in database """


class Person:
    def __init__(
        self,
        name: str = None,
        school_email: str = None,
        personal_email: str = None,
        active: bool = None,
        emplid: str = None,
        preferred_name: str = None,
        pronouns: str = None,
    ):
        self.uid = None  # generated by db
        self.name = name
        self.school_email = school_email
        self.personal_email = personal_email
        self.accept = active
        self.emplid = emplid
        self.preferred_name = preferred_name
        self.pronouns = pronouns
